### ISSUE TITLE
is there any demo, or code that I can use it to test my videos? Can it test in real-time?

### ISSUE THREAD

**Issue by qiumei1101** [happywu/Sequence-Level-Semantics-Aggregation#1]

**Comment by happywu** [comment]
I might add demo when I have time. 
I would suggest look at this [script](https://github.com/msracver/Flow-Guided-Feature-Aggregation/blob/master/fgfa_rfcn/demo.py) to write your own dataloader and perform testing.

**Comment by qiumei1101** [comment]
Ok. thanks. I will write that. By the way, can the model test the video in real-time?

**Comment by mamunir** [comment]
@qiumei1101 , were you able to run the demo by modifying FGFA?
