### ISSUE TITLE
bug of data augmentation

### ISSUE THREAD

**Issue by sunguanxiong** [happywu/Sequence-Level-Semantics-Aggregation#15]
In your code of augmentation:

https://github.com/happywu/Sequence-Level-Semantics-Aggregation/blob/c1efb0a7ba37394c14f32c5725bc5a0139c8651a/lib/utils/augmentations.py#L270

>>>  if overlap.min() < min_iou and max_iou < overlap.max():

In this line, the max_iou in INF. So max_iou will never be < overlap.max(). As a result, whatever the overlap is, the crop will be kept.

Is this a bug? Our you intend to keep all random crops?

**Comment by happywu** [comment]
Hi, yes, it should be a bug from the original code snippet. https://github.com/amdegroot/ssd.pytorch/issues/119.
