### ISSUE TITLE
Could you provide detailed introductions or explanation for the meanings of txt file inside /ImageSets/ folder?Thanks

### ISSUE THREAD

**Issue by TyroneLi** [happywu/Sequence-Level-Semantics-Aggregation#4]

**Comment by happywu** [comment]
For video data (VID), there is four fields: name /path of the video segment, start_frame_id, frame_idx, total length of the segment
For single frame data (DET), there is two fields: path of the image, start_frame_id (for consistent / convenience with video data)
You shall refer to    https://github.com/happywu/Sequence-Level-Semantics-Aggregation/blob/7ae05968bb9a7e3da3ca9722d1d13fe6306ffdbd/lib/dataset/imagenet_vid.py#L70-L87
for usage.
