### ISSUE TITLE
Testing without Data Augmentation

### ISSUE THREAD

**Issue by AlbertoSabater** [happywu/Sequence-Level-Semantics-Aggregation#9]
Hi! Is there any config file like [this one](https://github.com/happywu/Sequence-Level-Semantics-Aggregation/blob/master/experiments/selsa/cfgs/resnet_v1_101_rcnn_selsa_aug.yaml) to not perform data augmentation at the inference time? What should I modify to achieve it?

Thanks in advance!

**Comment by happywu** [comment]
Hi,
By default, testing does not use data augmentation. 
Data augmentation is only performed during training. Nothing needs to be modified.

**Comment by AlbertoSabater** [comment]
Thanks for the clarification!
